{% set name = "tranquilizer" %}
{% set version = "0.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 95a59c07b992fb0a733dfd3402039320fa3ff118c99bd9190e607367dfd2df07

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tranquilizer = tranquilizer.main:run

requirements:
  host:
    - python >=3.6, <3.10
    - pip
  run:
    - python >=3.6, <3.10
    - flask
    - werkzeug >=0.15,<=2.1.2
    - flask-restx
    - python-dateutil
    - flask-cors
    - flask-jwt-extended >=4

test:
  requires:
    - archspec
    - py-cpuinfo
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help
    - archspec cpu
    - cpuinfo

about:
  home: http://github.com/ContinuumIO/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Put your Python functions to REST; deploy a REST API with one line by decorating your functions.

extra:
  recipe-maintainers:
    - AlbertDeFusco
