{% set name = "tranquilizer" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 05e27d1fd61534efdd300ebaaa0828201121fae71886d1c8a287a99f870a36ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tranquilizer = tranquilizer.main:run

requirements:
  host:
    - python >=3.6, <3.13
    - pip
  run:
    - python >=3.6, <3.13
    - flask
    - werkzeug >=0.15,<=2.1.2
    - flask-restx
    - python-dateutil
    - flask-cors
    - flask-jwt-extended >=4

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/ContinuumIO/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Put your Python functions to REST; deploy a REST API with one line by decorating your functions.

extra:
  recipe-maintainers:
    - AlbertDeFusco
