{% set name = "tranquilizer" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e96f7671e9734ce362d37fb27ba27cd42d29ed402238888ea7492b9b7f788ac2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tranquilizer = tranquilizer.main:run

requirements:
  host:
    - python >=3.6, <3.10
    - pip
  run:
    - python >=3.6, <3.10
    - flask
    - werkzeug >=0.15, <2.0
    - flask-restx
    - python-dateutil
    - flask-cors
    - flask-jwt-extended >=4

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/ContinuumIO/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Put your Python functions to REST; deploy a REST API with one line by decorating your functions.

extra:
  recipe-maintainers:
    - AlbertDeFusco
