{% set name = "tranquilizer" %}
{% set version = "0.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58b64ff58ca1048c8fab45b389cfd339da738b14d0c8d4cba7c2ff4116907f7c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tranquilizer = tranquilizer.main:run

requirements:
  host:
    - python >=3.5, <3.9
    - pip
  run:
    - python >=3.5, <3.9
    - flask
    - werkzeug >=0.15, <2.0
    - flask-restx
    - python-dateutil
    - flask-cors

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/ContinuumIO/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Put your Python functions to REST; deploy a REST API with one line by decorating your functions.

extra:
  recipe-maintainers:
    - AlbertDeFusco
