{% set name = "tranquilizer" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 626306e7215c5df9e13b8201ed280d63711e8699a71a5903f4be93e0d5f4df17

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - tranquilizer = tranquilizer.main:run

requirements:
  host:
    - python >=3.6, <3.10
    - pip
  run:
    - python >=3.6, <3.10
    - flask
    - werkzeug >=0.15, <2.0
    - flask-restx
    - python-dateutil
    - flask-cors
    - flask-jwt-extended>=4

test:
  imports:
    - tranquilizer
  commands:
    - tranquilizer --help

about:
  home: http://github.com/ContinuumIO/tranquilizer
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Put your Python functions to REST; deploy a REST API with one line by decorating your functions.

extra:
  recipe-maintainers:
    - AlbertDeFusco
